###
GET http://localhost:8000/Employees HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Salary?restaurant=fogoDeChao HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Salary?restaurant=gamine HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Salary?restaurant=hookfish HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Salary?restaurant=zenYai HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Salary?restaurant=invalid HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Bonus?restaurant=fogoDeChao HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Bonus?restaurant=gamine HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Bonus?restaurant=hookfish HTTP/1.1

###
GET http://localhost:8000/Bonus?restaurant=zenYai HTTP/1.1
Authorization: bearer keyw9eMTC6oHYMQcJ

###
GET http://localhost:8000/Bonus?restaurant=null HTTP/1.1